apiVersion: v1
kind: Pod
metadata:
  name: calculator
spec:
  containers:
    - name: service
      image: quay.io/kubernetes-workshop/calculator-backend:latest
      ports:
        - containerPort: 8080
