kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: calculator-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: calculator-backend
    spec:
      containers:
        - name: service
          image: quay.io/kubernetes-workshop/calculator-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: calculator-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: calculator-backend
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: calculator-frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: calculator-frontend
    spec:
      containers:
        - name: service
          image: quay.io/kubernetes-workshop/calculator-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
          env:
            - name: 'CALCULATOR_BACKEND_BASE_URL'
              value: 'http://calculator-backend'
---
kind: Service
apiVersion: v1
metadata:
  name: calculator-frontend
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: calculator-frontend