apiVersion: v1
kind: Pod
metadata:
  name: my-happy-pod
spec:
  restartPolicy: Never
  containers:
    - name: service
      image: nginx:1.15
      ports:
        - containerPort: 80
          name: http
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 64Mi
