kind: Deployment
apiVersion: apps/v1
metadata:
  name: calculator-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: calculator-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calculator-backend
    spec:
      containers:
        - name: service
          image: quay.io/kubernetes-workshop/calculator-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 1000m, memory: 128Mi }
          livenessProbe: { httpGet: { path: /, port: 8080 } }
          readinessProbe: { httpGet: { path: /, port: 8080 } }
---
kind: Service
apiVersion: v1
metadata:
  name: calculator-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: calculator-backend
