kind: Deployment
apiVersion: apps/v1
metadata:
  name: calculator-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-frontend
  template:
    metadata:
      labels:
        app: calculator-frontend
    spec:
      containers:
        - name: service
          image: quay.io/kubernetes-workshop/calculator-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 1000m, memory: 128Mi }
          livenessProbe: { httpGet: { path: /, port: 3000 } }
          readinessProbe: { httpGet: { path: /, port: 3000 } }
          env:
            - name: "CALCULATOR_BACKEND_BASE_URL"
              value: "http://calculator-backend"
---
kind: Service
apiVersion: v1
metadata:
  name: calculator-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: calculator-frontend
