kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: service
          image: nginx:1.15
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 1000m, memory: 128Mi }
          livenessProbe: { httpGet: { path: /, port: 80 } }
          readinessProbe: { httpGet: { path: /, port: 80 } }
