kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-proxy
    spec:
      containers:
        - name: service
          image: nginx:1.15
          imagePullPolicy: Always
          env:
           - name: 'NGINX_HOST'
             value: 'hello-world.com'
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 1000m, memory: 128Mi }
          livenessProbe: { httpGet: { path: /, port: 80 } }
          readinessProbe: { httpGet: { path: /, port: 80 } }
