apiVersion: v1
kind: Pod
metadata:
  name: my-happy-pod
spec:
  restartPolicy: Never
  containers:
    - name: service
      image: nginx:1.15
      ports:
        - containerPort: 80
      resources:
        requests: { cpu: 100m, memory: 128Mi }
        limits: { cpu: 1000m, memory: 128Mi }
