apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
        - name: server
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: my-pw
            - name: MYSQL_DATABASE
              value: guestbook
          ports:
            - containerPort: 3306
          resources:
            limits: { cpu: 1000m, memory: 256Mi }
            requests: { cpu: 100m, memory: 256Mi }
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-storage
              subPath: data
  volumeClaimTemplates:
  - metadata:
      name: data-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources: { requests: { storage: 1Gi } }
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
