apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      containers:
        - name: server
          image: postgres:10.5
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: calculator
          ports:
            - containerPort: 5432
          resources:
            limits: { cpu: 1000m, memory: 256Mi }
            requests: { cpu: 100m, memory: 256Mi }
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-storage
              subPath: data
  volumeClaimTemplates:
  - metadata:
      name: data-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources: { requests: { storage: 1Gi } }
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
