repository: meisterplan/kubernetes-workshop
title: k8s workshop
description: Start with us your first kubernetes workloads!

remote_theme: pmarsceill/just-the-docs@v0.2.4
aux_links:
    "GitHub": "https://github.com/itdesign/kubernetes-workshop"
    "itdesign GmbH": "https://itdesign.de"

plugins:
  - jekyll-redirect-from
